exp_id: D11_img0020
data:
  file_name: /workspaces/codex-analysis/data/uterus/D11/img0020/img0020.qptiff

bftools:
  showinf_path: /workspaces/codex-analysis/bftools/showinf
tissue_extraction:
  n_tissue: -1
  downscale_factor: 64
  min_area: -1
  visualize: true
  output_dir: 
    /workspaces/codex-analysis/data/uterus/D11/img0020/processed_hubmap
  manual_mask_json: 
    /workspaces/codex-analysis/data/uterus/D11/img0020/processed_hubmap/hubmap_annotations
