exp_id: D16_img0036
data:
  file_name: /workspaces/codex-analysis/data/uterus/D16/img0036/img0036.qptiff

bftools:
  showinf_path: /workspaces/codex-analysis/bftools/showinf
tissue_extraction:
  n_tissue: -1
  downscale_factor: 64
  min_area: -1
  visualize: true
  output_dir: 
    /workspaces/codex-analysis/data/uterus/D16/img0036/processed_hubmap
  manual_mask_json: 
    /workspaces/codex-analysis/data/uterus/D16/img0036/processed_hubmap/hubmap_annotations
