exp_id: D18_img0042
data:
  file_name: /workspaces/codex-analysis/data/uterus/D18/img0042/img0042.qptiff

bftools:
  showinf_path: /workspaces/codex-analysis/bftools/showinf
tissue_extraction:
  n_tissue: -1
  downscale_factor: 64
  min_area: -1
  visualize: true
  output_dir: 
    /workspaces/codex-analysis/data/uterus/D18/img0042/processed_hubmap
  manual_mask_json: 
    /workspaces/codex-analysis/data/uterus/D18/img0042/processed_hubmap/hubmap_annotations
