exp_id: D17_18
data:
  file_name: 
    /workspaces/codex-analysis/data/Ovary/D17_18/redo_Scan1/Ovary_D17_D18_redo_Scan1.er.qptiff

bftools:
  showinf_path: /workspaces/codex-analysis/bftools/showinf
tissue_extraction:
  n_tissue: -1
  downscale_factor: 64
  min_area: -1
  visualize: true
  output_dir: 
    /workspaces/codex-analysis/data/Ovary/D17_18/redo_Scan1/processed_hubmap
  manual_mask_json: 
    /workspaces/codex-analysis/data/Ovary/D17_18/redo_Scan1/processed_hubmap/hubmap_annotations
