exp_id: D14_img0026
data:
  file_name: /workspaces/codex-analysis/data/uterus/D14/img0026/img0026.qptiff

bftools:
  showinf_path: /workspaces/codex-analysis/bftools/showinf
tissue_extraction:
  n_tissue: -1
  downscale_factor: 64
  min_area: -1
  visualize: true
  output_dir: 
    /workspaces/codex-analysis/data/uterus/D14/img0026/processed_hubmap
  manual_mask_json: 
    /workspaces/codex-analysis/data/uterus/D14/img0026/processed_hubmap/hubmap_annotations
