exp_id: D15_img0030
data:
  file_name: /workspaces/codex-analysis/data/uterus/D15/img0030/img0030.qptiff

bftools:
  showinf_path: /workspaces/codex-analysis/bftools/showinf
tissue_extraction:
  n_tissue: -1
  downscale_factor: 64
  min_area: -1
  visualize: true
  output_dir: 
    /workspaces/codex-analysis/data/uterus/D15/img0030/processed_hubmap
  manual_mask_json: 
    /workspaces/codex-analysis/data/uterus/D15/img0030/processed_hubmap/hubmap_annotations
