exp_id: D17_img0040
data:
  file_name: /workspaces/codex-analysis/data/uterus/D17/img0040/img0040.qptiff

bftools:
  showinf_path: /workspaces/codex-analysis/bftools/showinf
tissue_extraction:
  n_tissue: -1
  downscale_factor: 64
  min_area: -1
  visualize: true
  output_dir: 
    /workspaces/codex-analysis/data/uterus/D17/img0040/processed_hubmap
  manual_mask_json: 
    /workspaces/codex-analysis/data/uterus/D17/img0040/processed_hubmap/hubmap_annotations
